# Generated by Django 5.0.1 on 2024-05-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Project Coordinator'), (3, 'Supervisor'), (4, 'Student')], default=4),
        ),
    ]
