# Generated by Django 5.0.1 on 2024-05-29 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week6', '0003_alter_thesis_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'user_type': 4}, related_name='theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
