# Generated by Django 5.0.1 on 2024-05-29 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week6', '0004_alter_thesis_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'user_type': 4}, to=settings.AUTH_USER_MODEL),
        ),
    ]
