# Generated by Django 5.0.1 on 2024-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week6', '0007_remove_user_password1_remove_user_password2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Supervisor'), (3, 'Project Coordinator'), (4, 'Student')], default=4),
        ),
    ]
