# Generated by Django 5.0.1 on 2024-05-30 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week6', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='interested',
            field=models.ManyToManyField(limit_choices_to={'user_type': 4}, related_name='interested_theses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
