# Generated by Django 5.0.1 on 2024-05-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week6', '0009_thesis_interested_alter_thesis_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='thesis',
            field=models.ForeignKey(limit_choices_to={'is_approved': True}, on_delete=django.db.models.deletion.CASCADE, to='app_week6.thesis'),
        ),
    ]
