# Generated by Django 5.0.1 on 2024-05-30 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_week6', '0010_alter_group_thesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='interested',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 4}, null=True, related_name='interested_theses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 4}, null=True, related_name='theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
